name: CI

on:
  push:
    branches: [master]
  pull_request:
  workflow_dispatch:

jobs:
  gcc:
    name: gcc-${{ matrix.version }} ${{ matrix.build }}
    runs-on: ubuntu-26.04
    container:
      image: gcc:${{ matrix.version }}
      options: --cap-add=SYS_PTRACE --security-opt seccomp=unconfined
    strategy:
      fail-fast: false
      matrix:
        version: [15, 16]
        build: [sanitizers, release]
    env:
      MESON_ARGS: -Dwerror=true ${{ matrix.build == 'sanitizers' && '-Dbuildtype=debug -Db_sanitize=address,undefined' || '-Dbuildtype=release' }}
    steps:
      - uses: actions/checkout@v5
      - name: Install dependencies
        run: apt-get update && apt-get install -y --no-install-recommends meson pkgconf liburing-dev
      - name: Fetch poor_base
        run: git -c safe.directory="$PWD" submodule update --init subprojects/poor_base
      - name: Build
        run: |
          meson setup build $MESON_ARGS
          meson compile -C build
      - name: Test
        run: |
          meson test -C build --print-errorlogs
          ! grep -q '"result": "SKIP"' build/meson-logs/testlog.json

  clang:
    name: clang-${{ matrix.version }} ${{ matrix.build }}
    runs-on: ubuntu-26.04
    strategy:
      fail-fast: false
      matrix:
        version: [21, 22, 23]
        build: [sanitizers, release]
    env:
      CC: clang-${{ matrix.version }}
      MESON_ARGS: -Dwerror=true ${{ matrix.build == 'sanitizers' && '-Dbuildtype=debug -Db_sanitize=address,undefined -Db_lundef=false' || '-Dbuildtype=release' }}
    steps:
      - uses: actions/checkout@v5
      - name: Install dependencies
        run: |
          wget -qO llvm.sh https://apt.llvm.org/llvm.sh
          sudo bash llvm.sh ${{ matrix.version }}
          sudo apt-get install -y libclang-rt-${{ matrix.version }}-dev meson liburing-dev
      - name: Fetch poor_base
        run: git submodule update --init subprojects/poor_base
      - name: Build
        run: |
          meson setup build $MESON_ARGS
          meson compile -C build
      - name: Test
        run: |
          meson test -C build --print-errorlogs
          ! grep -q '"result": "SKIP"' build/meson-logs/testlog.json
